using Microsoft.EntityFrameworkCore.Migrations;

namespace GlassDoor.Migrations
{
    public partial class cityIdNotAutoGenerated : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Applications_Jobs_JobId",
                table: "Applications");

            migrationBuilder.DropForeignKey(
                name: "FK_Jobs_Cities_CityId",
                table: "Jobs");

            migrationBuilder.DropForeignKey(
                name: "FK_JobsDetails_Jobs_JobId",
                table: "JobsDetails");

            migrationBuilder.DropForeignKey(
                name: "FK_JobSkill_Jobs_JobsId",
                table: "JobSkill");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Jobs",
                table: "Jobs");

            migrationBuilder.DropIndex(
                name: "IX_Jobs_CityId",
                table: "Jobs");

            migrationBuilder.RenameColumn(
                name: "JobsId",
                table: "JobSkill",
                newName: "JobsCityId");

            migrationBuilder.RenameColumn(
                name: "JobId",
                table: "Applications",
                newName: "JobCityId");

            migrationBuilder.RenameIndex(
                name: "IX_Applications_JobId",
                table: "Applications",
                newName: "IX_Applications_JobCityId");

            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "Jobs",
                type: "int",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "int")
                .OldAnnotation("SqlServer:Identity", "1, 1");

            migrationBuilder.AddColumn<int>(
                name: "CityId1",
                table: "Jobs",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddPrimaryKey(
                name: "PK_Jobs",
                table: "Jobs",
                column: "CityId");

            migrationBuilder.CreateIndex(
                name: "IX_Jobs_CityId1",
                table: "Jobs",
                column: "CityId1");

            migrationBuilder.AddForeignKey(
                name: "FK_Applications_Jobs_JobCityId",
                table: "Applications",
                column: "JobCityId",
                principalTable: "Jobs",
                principalColumn: "CityId",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_Jobs_Cities_CityId1",
                table: "Jobs",
                column: "CityId1",
                principalTable: "Cities",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_JobsDetails_Jobs_JobId",
                table: "JobsDetails",
                column: "JobId",
                principalTable: "Jobs",
                principalColumn: "CityId",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_JobSkill_Jobs_JobsCityId",
                table: "JobSkill",
                column: "JobsCityId",
                principalTable: "Jobs",
                principalColumn: "CityId",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Applications_Jobs_JobCityId",
                table: "Applications");

            migrationBuilder.DropForeignKey(
                name: "FK_Jobs_Cities_CityId1",
                table: "Jobs");

            migrationBuilder.DropForeignKey(
                name: "FK_JobsDetails_Jobs_JobId",
                table: "JobsDetails");

            migrationBuilder.DropForeignKey(
                name: "FK_JobSkill_Jobs_JobsCityId",
                table: "JobSkill");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Jobs",
                table: "Jobs");

            migrationBuilder.DropIndex(
                name: "IX_Jobs_CityId1",
                table: "Jobs");

            migrationBuilder.DropColumn(
                name: "CityId1",
                table: "Jobs");

            migrationBuilder.RenameColumn(
                name: "JobsCityId",
                table: "JobSkill",
                newName: "JobsId");

            migrationBuilder.RenameColumn(
                name: "JobCityId",
                table: "Applications",
                newName: "JobId");

            migrationBuilder.RenameIndex(
                name: "IX_Applications_JobCityId",
                table: "Applications",
                newName: "IX_Applications_JobId");

            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "Jobs",
                type: "int",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "int")
                .Annotation("SqlServer:Identity", "1, 1");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Jobs",
                table: "Jobs",
                column: "Id");

            migrationBuilder.CreateIndex(
                name: "IX_Jobs_CityId",
                table: "Jobs",
                column: "CityId");

            migrationBuilder.AddForeignKey(
                name: "FK_Applications_Jobs_JobId",
                table: "Applications",
                column: "JobId",
                principalTable: "Jobs",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_Jobs_Cities_CityId",
                table: "Jobs",
                column: "CityId",
                principalTable: "Cities",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_JobsDetails_Jobs_JobId",
                table: "JobsDetails",
                column: "JobId",
                principalTable: "Jobs",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_JobSkill_Jobs_JobsId",
                table: "JobSkill",
                column: "JobsId",
                principalTable: "Jobs",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
